import { useEffect,useMemo,useState } from "react";
import { deleteStudentFee,getStudentFees,updateStudentFee,type StudentFee } from "../../api/studentFees";
import { getFeeStructures,type FeeStructure } from "../../api/feeStructures";
import { getStudents,type StudentLookup } from "../../api/lookups";
import StudentFeeForm from "../../components/studentFees/StudentFeeForm";
import { DangerButton,EmptyState,PageHeader,PrimaryButton } from "../../components/common/ModuleUi";

export default function StudentFees(){
 const [items,setItems]=useState<StudentFee[]>([]),[students,setStudents]=useState<StudentLookup[]>([]),[fees,setFees]=useState<FeeStructure[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const [a,s,f]=await Promise.all([getStudentFees(),getStudents(),getFeeStructures()]);setItems(a);setStudents(s);setFees(f);}catch(e:any){setError(e?.response?.data?.detail??"Unable to load student fees.");}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const st=(id:number)=>{const s=students.find(x=>x.id===id);return s?`${s.first_name} ${s.last_name}`:`Student #${id}`};const fee=(id:number)=>fees.find(x=>x.id===id)?.fee_type??`Fee #${id}`;const filtered=useMemo(()=>items.filter(x=>`${st(x.student_id)} ${fee(x.fee_structure_id)} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[items,students,fees,q]);const remove=async(id:number)=>{if(!confirm("Delete this student fee?"))return;try{await deleteStudentFee(id);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to delete.");}};const change=async(id:number,s:string)=>{try{await updateStudentFee(id,s);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to update.");}};
 return <div className="p-4 sm:p-6"><PageHeader title="Student Fees" description="Assign fee structures and track fee status." action={<PrimaryButton onClick={()=>setOpen(true)}>+ Assign Fee</PrimaryButton>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input className="mb-4 w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm" placeholder="Search student or fee..." value={q} onChange={e=>setQ(e.target.value)}/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center">Loading...</div>:!filtered.length?<EmptyState message="No student fees found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Fee</th><th className="px-5 py-3">Due</th><th className="px-5 py-3">Paid</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="px-5 py-4 font-medium">{st(x.student_id)}</td><td className="px-5 py-4">{fee(x.fee_structure_id)}</td><td className="px-5 py-4">₹{Number(x.amount_due).toLocaleString()}</td><td className="px-5 py-4">₹{Number(x.amount_paid).toLocaleString()}</td><td className="px-5 py-4"><select className="rounded-lg border px-2 py-1.5 text-xs" value={x.status} onChange={e=>void change(x.id,e.target.value)}>{["PENDING","PARTIAL","PAID","OVERDUE"].map(s=><option key={s}>{s}</option>)}</select></td><td className="px-5 py-4 text-right"><DangerButton onClick={()=>void remove(x.id)}>Delete</DangerButton></td></tr>)}</tbody></table></div>}</div>{open&&<StudentFeeForm onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
