import { useEffect, useMemo, useState } from "react";
import { Edit3, GraduationCap, MoreVertical, Plus, Search, Trash2 } from "lucide-react";
import { deleteStudent, getStudents, type Student } from "../../api/students";
import StudentForm from "../../components/students/StudentForm";

const errorText=(e:any)=>Array.isArray(e.response?.data?.detail)?e.response.data.detail.map((x:any)=>`${x.loc?.at(-1)??"Field"}: ${x.msg}`).join(", "):e.response?.data?.detail||"Something went wrong.";
function Students(){
 const [students,setStudents]=useState<Student[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Student|null>(null); const [deleting,setDeleting]=useState<number|null>(null);
 const load=async()=>{try{setLoading(true);setError("");setStudents(await getStudents());}catch(e){setError(errorText(e));}finally{setLoading(false);}}; useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>students.filter(s=>`${s.first_name} ${s.last_name} ${s.admission_no} ${s.phone??""}`.toLowerCase().includes(search.toLowerCase())),[students,search]);
 const remove=async(s:Student)=>{const ok=window.confirm(`Delete ${s.first_name} ${s.last_name}?\n\nThis will remove the student's school records and disable their login account. This action cannot be undone.`);if(!ok)return;try{setDeleting(s.id);await deleteStudent(s.id);await load();}catch(e){window.alert(errorText(e));}finally{setDeleting(null);}};
 return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Students</h1><p className="mt-1 text-sm text-slate-500">Manage admissions, student profiles and accounts.</p></div><button onClick={()=>{setEditing(null);setOpen(true)}} className="inline-flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700"><Plus size={18}/>Add Student</button></div>
 <div className="grid gap-4 sm:grid-cols-3"><Stat label="Total Students" value={students.length}/><Stat label="Active" value={students.filter(s=>s.status==="ACTIVE").length}/><Stat label="Inactive" value={students.filter(s=>s.status!=="ACTIVE").length}/></div>
 <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-4"><div className="relative max-w-lg"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, admission number or phone..." className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-4 text-sm outline-none focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-500/10"/></div></div>
 {loading?<div className="py-16 text-center text-sm text-slate-500">Loading students...</div>:error?<div className="m-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:filtered.length===0?<div className="flex flex-col items-center py-16"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-slate-100"><GraduationCap className="text-slate-400"/></div><p className="mt-4 font-semibold text-slate-700">No students found</p><p className="mt-1 text-sm text-slate-400">{search?"Try another search.":"Use Add Student to create the first record."}</p></div>:<div className="overflow-x-auto"><table className="w-full"><thead className="bg-slate-50/80"><tr>{["Student","Admission No.","Gender","Phone","Status","Action"].map((h,i)=><th key={h} className={`px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-slate-400 ${i===5?"text-right":""}`}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(s=><tr key={s.id} className="hover:bg-slate-50"><td className="px-6 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-50 font-bold text-blue-600">{s.first_name[0]?.toUpperCase()}</div><div><p className="text-sm font-semibold text-slate-800">{s.first_name} {s.last_name}</p><p className="text-xs text-slate-400">Student ID #{s.id}</p></div></div></td><td className="px-6 py-4 text-sm text-slate-600">{s.admission_no}</td><td className="px-6 py-4 text-sm text-slate-600">{s.gender||"—"}</td><td className="px-6 py-4 text-sm text-slate-600">{s.phone||"—"}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${s.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{s.status}</span></td><td className="px-6 py-4 text-right"><div className="inline-flex items-center gap-1"><button title="Edit student" onClick={()=>{setEditing(s);setOpen(true)}} className="rounded-lg p-2 text-slate-400 hover:bg-blue-50 hover:text-blue-600"><Edit3 size={17}/></button><button title="Delete student" disabled={deleting===s.id} onClick={()=>void remove(s)} className="rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:opacity-50">{deleting===s.id?<MoreVertical className="animate-pulse" size={17}/>:<Trash2 size={17}/>}</button></div></td></tr>)}</tbody></table></div>}
 </div>{open&&<StudentForm student={editing} onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>}
export default Students;
