import { useEffect,useMemo,useState } from "react";
import { deleteTimetable,getTimetables,type Timetable as TimetableItem } from "../../api/timetables";
import { getClasses,getSections,getSubjects,getTeachers,type ClassItem,type SectionItem,type SubjectLookup,type TeacherLookup } from "../../api/lookups";
import TimetableForm from "../../components/timetables/TimetableForm";
import { DangerButton,EmptyState,PageHeader,PrimaryButton } from "../../components/common/ModuleUi";

export default function Timetables(){
 const [items,setItems]=useState<TimetableItem[]>([]),[classes,setClasses]=useState<ClassItem[]>([]),[sections,setSections]=useState<SectionItem[]>([]),[subjects,setSubjects]=useState<SubjectLookup[]>([]),[teachers,setTeachers]=useState<TeacherLookup[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const [t,c,s,sub,te]=await Promise.all([getTimetables(),getClasses(),getSections(),getSubjects(),getTeachers()]);setItems(t);setClasses(c);setSections(s);setSubjects(sub);setTeachers(te);}catch(e:any){setError(e?.response?.data?.detail??"Unable to load timetables.");}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const n=(id:number,a:any,l:string)=>a.find((x:any)=>x.id===id)?.name??`${l} #${id}`;const teacher=(id:number)=>{const t=teachers.find(x=>x.id===id);return t?`${t.first_name} ${t.last_name}`:`Teacher #${id}`};const filtered=useMemo(()=>items.filter(x=>`${n(x.class_id,classes,"Class")} ${n(x.section_id,sections,"Section")} ${n(x.subject_id,subjects,"Subject")} ${teacher(x.teacher_id)} ${x.day_of_week} ${x.room??""}`.toLowerCase().includes(q.toLowerCase())),[items,classes,sections,subjects,teachers,q]);const remove=async(id:number)=>{if(!confirm("Delete this timetable entry?"))return;try{await deleteTimetable(id);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to delete.");}};
 return <div className="p-4 sm:p-6"><PageHeader title="Timetable" description="Manage class schedules and rooms." action={<PrimaryButton onClick={()=>setOpen(true)}>+ Add Timetable Entry</PrimaryButton>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input className="mb-4 w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm" placeholder="Search timetable..." value={q} onChange={e=>setQ(e.target.value)}/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center">Loading...</div>:!filtered.length?<EmptyState message="No timetable entries found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Class</th><th className="px-5 py-3">Section</th><th className="px-5 py-3">Subject</th><th className="px-5 py-3">Teacher</th><th className="px-5 py-3">Day</th><th className="px-5 py-3">Time</th><th className="px-5 py-3">Room</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="px-5 py-4 font-medium">{n(x.class_id,classes,"Class")}</td><td className="px-5 py-4">{n(x.section_id,sections,"Section")}</td><td className="px-5 py-4">{n(x.subject_id,subjects,"Subject")}</td><td className="px-5 py-4">{teacher(x.teacher_id)}</td><td className="px-5 py-4">{x.day_of_week}</td><td className="px-5 py-4">{x.start_time} – {x.end_time}</td><td className="px-5 py-4">{x.room??"—"}</td><td className="px-5 py-4 text-right"><DangerButton onClick={()=>void remove(x.id)}>Delete</DangerButton></td></tr>)}</tbody></table></div>}</div>{open&&<TimetableForm onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
