import { useEffect,useMemo,useState } from "react";
import { deleteAttendance,getAttendance,updateAttendance,type Attendance as AttendanceItem } from "../../api/attendance";
import { getStudents,getTeachers,type StudentLookup,type TeacherLookup } from "../../api/lookups";
import AttendanceForm from "../../components/attendance/AttendanceForm";
import { DangerButton,EmptyState,PageHeader,PrimaryButton } from "../../components/common/ModuleUi";

export default function Attendance(){
 const [items,setItems]=useState<AttendanceItem[]>([]),[students,setStudents]=useState<StudentLookup[]>([]),[teachers,setTeachers]=useState<TeacherLookup[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const [a,s,t]=await Promise.all([getAttendance(),getStudents(),getTeachers()]);setItems(a);setStudents(s);setTeachers(t);}catch(e:any){setError(e?.response?.data?.detail??"Unable to load attendance.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const student=(id:number)=>{const s=students.find(x=>x.id===id);return s?`${s.first_name} ${s.last_name}`:`Student #${id}`}; const teacher=(id:number)=>{const t=teachers.find(x=>x.id===id);return t?`${t.first_name} ${t.last_name}`:`Teacher #${id}`};
 const filtered=useMemo(()=>items.filter(x=>`${student(x.student_id)} ${x.status} ${x.date}`.toLowerCase().includes(q.toLowerCase())),[items,students,q]);
 const remove=async(id:number)=>{if(!confirm("Delete this attendance record?"))return;try{await deleteAttendance(id);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to delete.");}};
 const change=async(id:number,status:string)=>{try{await updateAttendance(id,status);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to update.");}};
 return <div className="p-4 sm:p-6"><PageHeader title="Attendance" description="Record and manage daily student attendance." action={<PrimaryButton onClick={()=>setOpen(true)}>+ Mark Attendance</PrimaryButton>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input className="mb-4 w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm" placeholder="Search student, date or status..." value={q} onChange={e=>setQ(e.target.value)}/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center">Loading...</div>:!filtered.length?<EmptyState message="No attendance records found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">Date</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Marked By</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="px-5 py-4 font-medium">{student(x.student_id)}</td><td className="px-5 py-4">{x.date}</td><td className="px-5 py-4"><select className="rounded-lg border px-2 py-1.5 text-xs" value={x.status} onChange={e=>void change(x.id,e.target.value)}>{["PRESENT","ABSENT","LATE","LEAVE"].map(s=><option key={s}>{s}</option>)}</select></td><td className="px-5 py-4">{teacher(x.marked_by)}</td><td className="px-5 py-4 text-right"><DangerButton onClick={()=>void remove(x.id)}>Delete</DangerButton></td></tr>)}</tbody></table></div>}</div>{open&&<AttendanceForm onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
