"""create marks table

Revision ID: 3cf351d7aff4
Revises: c31e513012ff
Create Date: 2026-09-26 15:55:38.504421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf351d7aff4'
down_revision: Union[str, Sequence[str], None] = 'c31e513012ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_subject_id', 'student_id', name='uq_marks_exam_subject_student')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marks')
    # ### end Alembic commands ###
