import { useEffect,useMemo,useState } from "react";
import { deleteHomeworkSubmission,getHomeworkSubmissions,reviewHomeworkSubmission,type HomeworkSubmission } from "../../api/homeworkSubmissions";
import { getHomework,type Homework as HomeworkItem } from "../../api/homework";
import { getStudents,type StudentLookup } from "../../api/lookups";
import HomeworkSubmissionForm from "../../components/homeworkSubmissions/HomeworkSubmissionForm";
import { DangerButton,EmptyState,PageHeader,PrimaryButton } from "../../components/common/ModuleUi";

export default function HomeworkSubmissions(){
 const [items,setItems]=useState<HomeworkSubmission[]>([]),[homework,setHomework]=useState<HomeworkItem[]>([]),[students,setStudents]=useState<StudentLookup[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");const [a,h,s]=await Promise.all([getHomeworkSubmissions(),getHomework(),getStudents()]);setItems(a);setHomework(h);setStudents(s);}catch(e:any){setError(e?.response?.data?.detail??"Unable to load submissions.");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const hw=(id:number)=>homework.find(x=>x.id===id)?.title??`Homework #${id}`;const st=(id:number)=>{const s=students.find(x=>x.id===id);return s?`${s.first_name} ${s.last_name}`:`Student #${id}`};
 const filtered=useMemo(()=>items.filter(x=>`${hw(x.homework_id)} ${st(x.student_id)} ${x.status}`.toLowerCase().includes(q.toLowerCase())),[items,homework,students,q]);
 const review=async(id:number,status:string)=>{try{await reviewHomeworkSubmission(id,{status});await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to review submission.");}};
 const remove=async(id:number)=>{if(!confirm("Delete this submission?"))return;try{await deleteHomeworkSubmission(id);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to delete.");}};
 return <div className="p-4 sm:p-6"><PageHeader title="Homework Submissions" description="Review submitted homework and feedback status." action={<PrimaryButton onClick={()=>setOpen(true)}>+ Add Submission</PrimaryButton>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input className="mb-4 w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm" placeholder="Search..." value={q} onChange={e=>setQ(e.target.value)}/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center">Loading...</div>:!filtered.length?<EmptyState message="No submissions found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Homework</th><th className="px-5 py-3">Student</th><th className="px-5 py-3">Submitted</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="px-5 py-4 font-medium">{hw(x.homework_id)}</td><td className="px-5 py-4">{st(x.student_id)}</td><td className="px-5 py-4">{x.submitted_at?new Date(x.submitted_at).toLocaleString():"—"}</td><td className="px-5 py-4"><select className="rounded-lg border px-2 py-1.5 text-xs" value={x.status} onChange={e=>void review(x.id,e.target.value)}>{["SUBMITTED","REVIEWED","LATE","REJECTED"].map(s=><option key={s}>{s}</option>)}</select></td><td className="px-5 py-4 text-right"><DangerButton onClick={()=>void remove(x.id)}>Delete</DangerButton></td></tr>)}</tbody></table></div>}</div>{open&&<HomeworkSubmissionForm onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
