import { useEffect,useMemo,useState } from "react";
import { deletePayment,getPayments,type Payment } from "../../api/payments";
import PaymentForm from "../../components/payments/PaymentForm";
import { DangerButton,EmptyState,PageHeader,PrimaryButton } from "../../components/common/ModuleUi";

export default function Payments(){
 const [items,setItems]=useState<Payment[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{try{setLoading(true);setError("");setItems(await getPayments());}catch(e:any){setError(e?.response?.data?.detail??"Unable to load payments.");}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.receipt_no} ${x.method} ${x.student_fee_id}`.toLowerCase().includes(q.toLowerCase())),[items,q]);const remove=async(id:number)=>{if(!confirm("Delete this payment? The linked fee balance will be recalculated."))return;try{await deletePayment(id);await load();}catch(e:any){setError(e?.response?.data?.detail??"Unable to delete.");}};
 return <div className="p-4 sm:p-6"><PageHeader title="Payments" description="Record and review fee payments." action={<PrimaryButton onClick={()=>setOpen(true)}>+ Record Payment</PrimaryButton>}/>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<input className="mb-4 w-full max-w-lg rounded-xl border border-slate-300 px-4 py-2.5 text-sm" placeholder="Search receipt, method or fee ID..." value={q} onChange={e=>setQ(e.target.value)}/><div className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading?<div className="p-8 text-center">Loading...</div>:!filtered.length?<EmptyState message="No payments found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Receipt</th><th className="px-5 py-3">Student Fee</th><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Method</th><th className="px-5 py-3">Paid At</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{filtered.map(x=><tr key={x.id}><td className="px-5 py-4 font-medium">{x.receipt_no}</td><td className="px-5 py-4">#{x.student_fee_id}</td><td className="px-5 py-4">₹{Number(x.amount).toLocaleString()}</td><td className="px-5 py-4">{x.method}</td><td className="px-5 py-4">{new Date(x.paid_at).toLocaleString()}</td><td className="px-5 py-4 text-right"><DangerButton onClick={()=>void remove(x.id)}>Delete</DangerButton></td></tr>)}</tbody></table></div>}</div>{open&&<PaymentForm onClose={()=>setOpen(false)} onSuccess={load}/>}</div>;
}
